name: Deploy to Digital Ocean

on:
  push:
    branches: [main]
    paths: ['apps/api/**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          cd apps/api
          npm ci
          
      - name: Run tests
        run: |
          cd apps/api
          npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200
        
      - name: Build container image
        run: |
          cd apps/api
          docker build -t registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/teacha-api:$(echo $GITHUB_SHA | head -c7) .
          docker build -t registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/teacha-api:latest .
          
      - name: Push image to DigitalOcean Container Registry
        run: |
          docker push registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/teacha-api:$(echo $GITHUB_SHA | head -c7)
          docker push registry.digitalocean.com/${{ secrets.REGISTRY_NAME }}/teacha-api:latest
          
      - name: Deploy to DigitalOcean App Platform
        run: |
          doctl apps create-deployment ${{ secrets.APP_ID }} --wait
